# Generated by Django 3.2.4 on 2021-07-02 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_episodes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='watched_list',
            field=models.ManyToManyField(to='anime.Anime'),
        ),
    ]
