# Generated by Django 3.2.4 on 2021-07-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_episodes'),
        ('users', '0002_customuser_watched_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='watched_list',
            field=models.ManyToManyField(blank=True, to='anime.Anime'),
        ),
    ]
