# Generated by Django 3.2.4 on 2021-07-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_anime_country_of_origin'),
        ('users', '0003_alter_customuser_watched_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='watched_list',
            field=models.ManyToManyField(blank=True, related_name='animes', to='anime.Anime'),
        ),
    ]
