# Generated by Django 3.2.4 on 2021-06-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_series', models.BooleanField(default=True)),
                ('episodes', models.IntegerField(blank=True)),
                ('cover', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('unspecified', 'Unspecified'), ('bad', 'Bad'), ('okay', 'Okay'), ('good', 'Good'), ('nice', 'Nice'), ('masterpiece', 'Masterpiece')], default='unspecified', max_length=20, verbose_name='Anime Score')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='anime.anime')),
            ],
        ),
    ]
