# Generated by Django 3.2.4 on 2021-07-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_auto_20210630_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='cover',
        ),
    ]
