# Generated by Django 3.2.4 on 2021-07-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
