# Generated by Django 3.2.4 on 2021-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_anime_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='time',
            field=models.DateField(null=True),
        ),
    ]
