# Generated by Django 3.2.4 on 2021-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_anime_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
