# Generated by Django 3.2.4 on 2021-07-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_alter_anime_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='country_of_origin',
            field=models.CharField(blank=True, choices=[('japan', 'Japan'), ('south korea', 'South Korea'), ('china', 'China'), ('usa', 'USA')], max_length=20, verbose_name='Country of origin'),
        ),
    ]
